version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db_data/:/data/db/
    networks:
      - REDEMONGO

  mongo-express:
    image: mongo-express:latest
    restart: always
    container_name: mongo_ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/  # Updating to use service name
    networks:
      - REDEMONGO

networks:
  REDEMONGO:
    external: true

