version: '3.8'

services:
  mongo-dev:
    image: mongo:latest
    container_name: mongo_dev
    networks:
      - REDEMONGO
    volumes:
      - ./db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    labels:
      - "com.docker.compose.project=mongo-project"
      - "com.docker.compose.service=mongo-dev"
      - "com.docker.volume.name=mongo_dev"

  mongo-ui:
    image: mongo-express:latest
    container_name: mongo_ui
    networks:
      - REDEMONGO
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo_dev:27017/
    labels:
      - "com.docker.compose.project=mongo-project"
      - "com.docker.compose.service=mongo-ui"
      - "com.docker.volume.name=mongo_ui"

networks:
  REDEMONGO:
    driver: bridge


